version: '2'

networks:
    brownie-net:
        driver: bridge

services:
    mysql_db:
        image: mysql:5.7
        container_name: mysql_brownie
        hostname: mysql_brownie
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "Brownie123"
            MYSQL_DATABASE: 'brownie_wp'
            MYSQL_USER: 'brownie'
            MYSQL_PASSWORD: 'brownie001'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - /tmp/db:/var/lib/mysqld
            - ./mysql/grant.sh:/grant.sh
        entrypoint: /grant.sh
        networks: 
            - brownie-net


    wordpress:
        image: wordpress:latest
        container_name: wordpress_brownie
        hostname: wordpress_brownie
        ports: 
            - 80:80
        links: 
         - mysql_db
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql_db:3306
            WORDPRESS_DB_NAME: 'brownie_wp'
            WORDPRESS_DB_USER: 'brownie_wp'
            WORDPRESS_DB_PASSWORD: 'brownie001'
        networks:
            - brownie-net
