mysql:
    image: mysql:5.7
    container_name: mysql_brownie
    ports:
    - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: "Brownie123"
        MYSQL_DATABASE: 'brownie_wp'
        MYSQL_USER: 'brownie'
        MYSQL_PASSWORD: 'brownie001'
    volumes:
        - /storage/docker/mysql-datadir:/var/lib/mysqld"
    
     