mysql_db:
    image: mysql:5.7
    container_name: mysql_brownie
    ports:
    - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: "Brownie123"
        MYSQL_DATABASE: 'brownie_wp'
        MYSQL_USER: 'brownie'
        MYSQL_PASSWORD: 'brownie001'
    volumes:
    - /var/lib/mysql/docker/db:/var/lib/mysqld    

wordpress:
    image: wordpress:latest
    container_name: wordpress_brownie
    ports:
    - 80:80
    links: 
    - mysql_db
    restart: always
    environment:
        WORDPRESS_DB_HOST: mysql_db:3306
        WORDPRESS_DB_NAME: 'brownie_wp'
        WORDPRESS_DB_USER: 'brownie_wp'
        WORDPRESS_DB_PASSWORD: 'brownie001'    
