# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s # By default, scrape targets every 5 seconds.
  external_labels:
      monitor: 'Brownie_Project'

rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
        - targets: ['cadvisor:8080']

  - job_name: 'container-exporter'
    scrape_interval: 5s
    static_configs:
        - targets: ['container-exporter:9104']
